### ISSUE TITLE
[BUG] <Некорректный призыв-отзыв техники и питомцев>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#20]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [ ] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [ ] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Any additional context for this bug**

**Comment by Black-Judge** [comment]
после внесения последних изменений ситуация с кораблями не поменялась, Тримаран появляется без анимации, нельзя встать за штурвал, паруса отсутствуют, отозвать нельзя.
В логе такая ошибка
10:15:19 [ERROR] TaskManager - System.NullReferenceException: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at AAEmu.Game.Core.Packets.G2C.SCSlaveStatusPacket..ctor(Slave slave) in /server/AAEmuDev/AAEmu.Game/Core/Packets/G2C/SCSlaveStatusPacket.cs:line 17
   at AAEmu.Game.Models.Game.Units.Slave.AddVisibleObject(Character character) in /server/AAEmuDev/AAEmu.Game/Models/Game/Units/Slave.cs:line 599
   at AAEmu.Game.Models.Game.World.Region.AddToCharacters(GameObject obj) in /server/AAEmuDev/AAEmu.Game/Models/Game/World/Region.cs:line 164
   at AAEmu.Game.Core.Managers.World.WorldManager.AddVisibleObject(GameObject obj) in /server/AAEmuDev/AAEmu.Game/Core/Managers/World/WorldManager.cs:line 927
   at AAEmu.Game.Models.Game.World.GameObject.Show() in /server/AAEmuDev/AAEmu.Game/Models/Game/World/GameObject.cs:line 80
   at AAEmu.Game.Models.Game.World.GameObject.Spawn() in /server/AAEmuDev/AAEmu.Game/Models/Game/World/GameObject.cs:line 67
   at AAEmu.Game.Core.Managers.SlaveManager.Create(Character owner, SlaveSpawner useSpawner, UInt32 templateId, Item item, Transform positionOverride) in /server/AAEmuDev/AAEmu.Game/Core/Managers/SlaveManager.cs:line 665
   at AAEmu.Game.Core.Managers.SlaveManager.Create(Character owner, SkillItem skillData, Transform positionOverride) in /server/AAEmuDev/AAEmu.Game/Core/Managers/SlaveManager.cs:line 348
   at AAEmu.Game.Models.Game.Skills.Effects.SpecialEffects.SpawnSlave.Execute(BaseUnit caster, SkillCaster casterObj, BaseUnit target, SkillCastTarget targetObj, CastAction castObj, Skill skill, SkillObject skillObject, DateTime time, Int32 value1, Int32 value2, Int32 value3, Int32 value4) in /server/AAEmuDev/AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/SpawnSlave.cs:line 32
   at AAEmu.Game.Models.Game.Skills.Effects.SpecialEffect.Apply(BaseUnit caster, SkillCaster casterObj, BaseUnit target, SkillCastTarget targetObj, CastAction castObj, EffectSource source, SkillObject skillObject, DateTime time, CompressedGamePackets packetBuilder) in /server/AAEmuDev/AAEmu.Game/Models/Game/Skills/Effects/SpecialEffect.cs:line 49
   at AAEmu.Game.Models.Game.Skills.Skill.ApplyEffects(BaseUnit caster, SkillCaster casterCaster, BaseUnit targetSelf, SkillCastTarget targetCaster, SkillObject skillObject) in /server/AAEmuDev/AAEmu.Game/Models/Game/Skills/Skill.cs:line 1025
   at AAEmu.Game.Models.Game.Skills.Skill.ScheduleEffects(BaseUnit caster, SkillCaster casterCaster, BaseUnit target, SkillCastTarget targetCaster, SkillObject skillObject) in /server/AAEmuDev/AAEmu.Game/Models/Game/Skills/Skill.cs:line 756
   at AAEmu.Game.Models.Game.Skills.Skill.Cast(BaseUnit caster, SkillCaster casterCaster, BaseUnit target, SkillCastTarget targetCaster, SkillObject skillObject) in /server/AAEmuDev/AAEmu.Game/Models/Game/Skills/Skill.cs:line 651
   at AAEmu.Game.Models.Tasks.Skills.CastTask.Execute() in /server/AAEmuDev/AAEmu.Game/Models/Tasks/Skills/CastTask.cs:line 27
   at AAEmu.Game.Core.Managers.TaskJob.Execute(IJobExecutionContext context) in /server/AAEmuDev/AAEmu.Game/Core/Managers/TaskManager.cs:line 276
