### ISSUE TITLE
[BUG] <Вылет игрового клиента при попытке одеть экипировку на питомца>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#23]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

При попытке одеть предметы экипировки на питомца клиент вылетает с ошибкой, а в терминале пишет сам текст ошибки

**Steps to reproduce**

Призвать питомца, создать предметы экипировки для питомца себе в инвентарь, попытаться одеть предметы экипировки на питомца.

**Expected behavior**

**Screenshots**

https://youtu.be/XmxBocJGkLM

**Any additional context for this bug**

Текст ошибки в терминале
14:38:52 [ERROR] PacketMarshaler - GamePacket: C->S type 00F .C2G.CSChangeMateEquipmentPacket 
14:38:52 [FATAL] PacketMarshaler - AAEmu.Commons.Exceptions.MarshalException: Marshal exception AAEmu.Commons.Exceptions.MarshalException: Marshal exception
   at AAEmu.Commons.Network.PacketStream.ReadInt64() in /server/AAEmuDev/AAEmu.Commons/Network/PacketStream.cs:line 397
   at AAEmu.Commons.Network.PacketStream.ReadDateTime() in /server/AAEmuDev/AAEmu.Commons/Network/PacketStream.cs:line 522
   at AAEmu.Game.Models.Game.Items.EquipItem.Read(PacketStream stream) in /server/AAEmuDev/AAEmu.Game/Models/Game/Items/EquipItem.cs:line 70
   at AAEmu.Game.Core.Packets.C2G.CSChangeMateEquipmentPacket.Read(PacketStream stream) in /server/AAEmuDev/AAEmu.Game/Core/Packets/C2G/CSChangeMateEquipmentPacket.cs:line 44
   at AAEmu.Game.Core.Network.Game.GamePacket.Decode(PacketStream ps) in /server/AAEmuDev/AAEmu.Game/Core/Network/Game/GamePacket.cs:line 125
14:38:52 [ERROR] GameProtocolHandler - AAEmu.Commons.Exceptions.MarshalException: Marshal exception AAEmu.Commons.Exceptions.MarshalException: Marshal exception
   at AAEmu.Commons.Network.PacketStream.ReadInt64() in /server/AAEmuDev/AAEmu.Commons/Network/PacketStream.cs:line 397
   at AAEmu.Commons.Network.PacketStream.ReadDateTime() in /server/AAEmuDev/AAEmu.Commons/Network/PacketStream.cs:line 522
   at AAEmu.Game.Models.Game.Items.EquipItem.Read(PacketStream stream) in /server/AAEmuDev/AAEmu.Game/Models/Game/Items/EquipItem.cs:line 70
   at AAEmu.Game.Core.Packets.C2G.CSChangeMateEquipmentPacket.Read(PacketStream stream) in /server/AAEmuDev/AAEmu.Game/Core/Packets/C2G/CSChangeMateEquipmentPacket.cs:line 44
   at AAEmu.Game.Core.Network.Game.GamePacket.Decode(PacketStream ps) in /server/AAEmuDev/AAEmu.Game/Core/Network/Game/GamePacket.cs:line 125
   at AAEmu.Game.Core.Network.Game.GameProtocolHandler.OnReceive(GameConnection connection, Byte[] buf, Int32 bytes) in /server/AAEmuDev/AAEmu.Game/Core/Network/Game/GameProtocolHandler.cs:line 171

14:38:52 [ERROR] GameProtocolHandler - AAEmu.Commons.Exceptions.MarshalException: Marshal exception AAEmu.Commons.Exceptions.MarshalException: Marshal exception
   at AAEmu.Commons.Network.PacketStream.ReadInt64() in /server/AAEmuDev/AAEmu.Commons/Network/PacketStream.cs:line 397
   at AAEmu.Commons.Network.PacketStream.ReadDateTime() in /server/AAEmuDev/AAEmu.Commons/Network/PacketStream.cs:line 522
   at AAEmu.Game.Models.Game.Items.EquipItem.Read(PacketStream stream) in /server/AAEmuDev/AAEmu.Game/Models/Game/Items/EquipItem.cs:line 70
   at AAEmu.Game.Core.Packets.C2G.CSChangeMateEquipmentPacket.Read(PacketStream stream) in /server/AAEmuDev/AAEmu.Game/Core/Packets/C2G/CSChangeMateEquipmentPacket.cs:line 44
   at AAEmu.Game.Core.Network.Game.GamePacket.Decode(PacketStream ps) in /server/AAEmuDev/AAEmu.Game/Core/Network/Game/GamePacket.cs:line 125
   at AAEmu.Game.Core.Network.Game.GameProtocolHandler.OnReceive(GameConnection connection, Byte[] buf, Int32 bytes) in /server/AAEmuDev/AAEmu.Game/Core/Network/Game/GameProtocolHandler.cs:line 171

**Comment by Black-Judge** [comment]
в некоторых случаях также вместе с клиентом вылетает сам игровой сервер
