### ISSUE TITLE
[BUG] <Баг с прокатом авто в Мираже>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#80]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

Проявился баг с прокатом авто в мираже, тестовый болид можно вызвать, но если попытаться занять место водителя то клиент закрывается с ошибкой.

Сообщения в логе:

09:49:52 [ERROR] PacketMarshaler - GamePacket: C->S type 039 .C2G.CSBindSlavePacket 
09:49:52 [FATAL] PacketMarshaler - System.Collections.Generic.KeyNotFoundException: The given key '119' was not present in the dictionary. System.Collections.Generic.KeyNotFoundException: The given key '119' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AAEmu.Game.Core.Managers.SlaveManager.BindSlave(GameConnection connection, UInt32 tlId) in /server/AAEmuRage/AAEmu.Game/Core/Managers/SlaveManager.cs:line 236
   at AAEmu.Game.Core.Packets.C2G.CSBindSlavePacket.Read(PacketStream stream) in /server/AAEmuRage/AAEmu.Game/Core/Packets/C2G/CSBindSlavePacket.cs:line 18
   at AAEmu.Game.Core.Network.Game.GamePacket.Decode(PacketStream ps) in /server/AAEmuRage/AAEmu.Game/Core/Network/Game/GamePacket.cs:line 149
   at AAEmu.Game.Core.Network.Game.GameProtocolHandler.OnReceive(GameConnection connection, Byte[] buf, Int32 bytes) in /server/AAEmuRage/AAEmu.Game/Core/Network/Game/GameProtocolHandler.cs:line 171
09:49:52 [ERROR] GameProtocolHandler - System.Collections.Generic.KeyNotFoundException: The given key '119' was not present in the dictionary. System.Collections.Generic.KeyNotFoundException: The given key '119' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AAEmu.Game.Core.Managers.SlaveManager.BindSlave(GameConnection connection, UInt32 tlId) in /server/AAEmuRage/AAEmu.Game/Core/Managers/SlaveManager.cs:line 236
   at AAEmu.Game.Core.Packets.C2G.CSBindSlavePacket.Read(PacketStream stream) in /server/AAEmuRage/AAEmu.Game/Core/Packets/C2G/CSBindSlavePacket.cs:line 18
   at AAEmu.Game.Core.Network.Game.GamePacket.Decode(PacketStream ps) in /server/AAEmuRage/AAEmu.Game/Core/Network/Game/GamePacket.cs:line 149
   at AAEmu.Game.Core.Network.Game.GameProtocolHandler.OnReceive(GameConnection connection, Byte[] buf, Int32 bytes) in /server/AAEmuRage/AAEmu.Game/Core/Network/Game/GameProtocolHandler.cs:line 171

**Steps to reproduce**

Зайти в игру персонажем, переместиться в Мираж, вызвать болид для теста, попытаться занять место водителя.

**Expected behavior**

**Screenshots**

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Исправил в 4f54aa230d041a9af91abc88c564c7555c43f91c
